# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Commandr CLI
site_url: https://LegitCirtuitz.github.io/cmdrcli/
site_author: LegitCirtuitz
site_description: Documentation for the Commandr CLI and related projects.
edit_uri: edit/main/docs/

# Repository
repo_name: LegitCirtuitz/cmdrcli
repo_url: https://github.com/LegitCirtuitz/cmdrcli

# Copyright
copyright: Copyright &copy; 2026 LegitCirtuitz

# Configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

# Style Links
extra_css:
  - stylesheets/custom_footer.css

# Plugins
plugins:
  - blog:
      post_readtime: true
      post_excerpt: optional
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LegitCirtuitz
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EMM2v5BW4v
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@ItsCirtwitz

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: LegitCirtuitz
      repo: cmdrcli
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: main/index.md
      - Documentation:
          - What is Commandr CLI?: main/documentation/cmdrinfo.md
          - Contributing Related: main/contributedocs.md
          - License: main/license.md
  - Blog: blog/index.md
  - Legal:
      - Legal Notice: legal/legal.md
      - Privacy Policy: legal/privacypol.md
      - Terms of Service: legal/tos.md
