# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Commandr CLI
site_url: https://LegitCirtuitz.github.io/cmdrcli/

theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)" # Fixed to light
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.tabs
    - search.suggest
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LegitCirtuitz
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EMM2v5BW4v
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@ItsCirtwitz

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: zh
          name: 简体中文
          build: true
        - locale: zh-Hant
          name: 繁體中文
          build: true
        - locale: ja
          name: 日本語
          build: true
        - locale: ko
          name: 한국어
          build: true
        - locale: pt
          name: Português
          build: true
        - locale: de
          name: Deutsch
          build: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
